<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use App\Models\Task;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Task::insert([
            [
                'client_id' => 1,
                'persona_contacto' => 'Contacto 1',
                'telefono_contacto' => '600123456',
                'descripcion' => 'Descripción de la tarea 1',
                'correo_electronico' => 'contacto1@example.com',
                'direccion' => 'Calle Falsa 123',
                'poblacion' => 'Madrid',
                'codigo_postal' => '28001',
                'provincia' => 1,
                'estado' => 'P',
                'fecha_creacion' => now(),
                'operario_encargado' => 'Operario 1',
                'fecha_realizacion' => '2025-03-10',
                'anotaciones_anteriores' => 'Anotaciones anteriores de la tarea 1',
                'anotaciones_posteriores' => 'Anotaciones posteriores de la tarea 1',
                'fichero_resumen' => 'resumen1.pdf',
            ],
            [
                'client_id' => 2,
                'persona_contacto' => 'Contacto 2',
                'telefono_contacto' => '600654321',
                'descripcion' => 'Descripción de la tarea 2',
                'correo_electronico' => 'contacto2@example.com',
                'direccion' => 'Avenida Siempre Viva 742',
                'poblacion' => 'Barcelona',
                'codigo_postal' => '08001',
                'provincia' => 2,
                'estado' => 'R',
                'fecha_creacion' => now(),
                'operario_encargado' => 'Operario 2',
                'fecha_realizacion' => '2025-03-15',
                'anotaciones_anteriores' => 'Anotaciones anteriores de la tarea 2',
                'anotaciones_posteriores' => 'Anotaciones posteriores de la tarea 2',
                'fichero_resumen' => 'resumen2.pdf',
            ],
            [
                'client_id' => 3,
                'persona_contacto' => 'Contacto 3',
                'telefono_contacto' => '600112233',
                'descripcion' => 'Descripción de la tarea 3',
                'correo_electronico' => 'contacto3@example.com',
                'direccion' => 'Calle Luna 45',
                'poblacion' => 'Valencia',
                'codigo_postal' => '46001',
                'provincia' => 3,
                'estado' => 'C',
                'fecha_creacion' => now(),
                'operario_encargado' => 'Operario 3',
                'fecha_realizacion' => '2025-03-20',
                'anotaciones_anteriores' => 'Anotaciones anteriores de la tarea 3',
                'anotaciones_posteriores' => 'Anotaciones posteriores de la tarea 3',
                'fichero_resumen' => 'resumen3.pdf',
            ],
            [
                'client_id' => 4,
                'persona_contacto' => 'Contacto 4',
                'telefono_contacto' => '600443322',
                'descripcion' => 'Descripción de la tarea 4',
                'correo_electronico' => 'contacto4@example.com',
                'direccion' => 'Calle Sol 67',
                'poblacion' => 'Sevilla',
                'codigo_postal' => '41001',
                'provincia' => 4,
                'estado' => 'P',
                'fecha_creacion' => now(),
                'operario_encargado' => 'Operario 4',
                'fecha_realizacion' => '2025-03-25',
                'anotaciones_anteriores' => 'Anotaciones anteriores de la tarea 4',
                'anotaciones_posteriores' => 'Anotaciones posteriores de la tarea 4',
                'fichero_resumen' => 'resumen4.pdf',
            ],
            [
                'client_id' => 5,
                'persona_contacto' => 'Contacto 5',
                'telefono_contacto' => '600556677',
                'descripcion' => 'Descripción de la tarea 5',
                'correo_electronico' => 'contacto5@example.com',
                'direccion' => 'Calle Estrella 89',
                'poblacion' => 'Zaragoza',
                'codigo_postal' => '50001',
                'provincia' => 5,
                'estado' => 'R',
                'fecha_creacion' => now(),
                'operario_encargado' => 'Operario 5',
                'fecha_realizacion' => '2025-03-30',
                'anotaciones_anteriores' => 'Anotaciones anteriores de la tarea 5',
                'anotaciones_posteriores' => 'Anotaciones posteriores de la tarea 5',
                'fichero_resumen' => 'resumen5.pdf',
            ],
            [
                'client_id' => 6,
                'persona_contacto' => 'Contacto 6',
                'telefono_contacto' => '600998877',
                'descripcion' => 'Descripción de la tarea 6',
                'correo_electronico' => 'contacto6@example.com',
                'direccion' => 'Calle Cometa 101',
                'poblacion' => 'Bilbao',
                'codigo_postal' => '48001',
                'provincia' => 6,
                'estado' => 'C',
                'fecha_creacion' => now(),
                'operario_encargado' => 'Operario 6',
                'fecha_realizacion' => '2025-04-05',
                'anotaciones_anteriores' => 'Anotaciones anteriores de la tarea 6',
                'anotaciones_posteriores' => 'Anotaciones posteriores de la tarea 6',
                'fichero_resumen' => 'resumen6.pdf',
            ],
            [
                'client_id' => 7,
                'persona_contacto' => 'Contacto 7',
                'telefono_contacto' => '600223344',
                'descripcion' => 'Descripción de la tarea 7',
                'correo_electronico' => 'contacto7@example.com',
                'direccion' => 'Calle Planeta 202',
                'poblacion' => 'Málaga',
                'codigo_postal' => '29001',
                'provincia' => 7,
                'estado' => 'P',
                'fecha_creacion' => now(),
                'operario_encargado' => 'Operario 7',
                'fecha_realizacion' => '2025-04-10',
                'anotaciones_anteriores' => 'Anotaciones anteriores de la tarea 7',
                'anotaciones_posteriores' => 'Anotaciones posteriores de la tarea 7',
                'fichero_resumen' => 'resumen7.pdf',
            ],
            [
                'client_id' => 8,
                'persona_contacto' => 'Contacto 8',
                'telefono_contacto' => '600667788',
                'descripcion' => 'Descripción de la tarea 8',
                'correo_electronico' => 'contacto8@example.com',
                'direccion' => 'Calle Galaxia 303',
                'poblacion' => 'Murcia',
                'codigo_postal' => '30001',
                'provincia' => 8,
                'estado' => 'R',
                'fecha_creacion' => now(),
                'operario_encargado' => 'Operario 8',
                'fecha_realizacion' => '2025-04-15',
                'anotaciones_anteriores' => 'Anotaciones anteriores de la tarea 8',
                'anotaciones_posteriores' => 'Anotaciones posteriores de la tarea 8',
                'fichero_resumen' => 'resumen8.pdf',
            ],
            [
                'client_id' => 9,
                'persona_contacto' => 'Contacto 9',
                'telefono_contacto' => '600334455',
                'descripcion' => 'Descripción de la tarea 9',
                'correo_electronico' => 'contacto9@example.com',
                'direccion' => 'Calle Universo 404',
                'poblacion' => 'Valladolid',
                'codigo_postal' => '47001',
                'provincia' => 9,
                'estado' => 'C',
                'fecha_creacion' => now(),
                'operario_encargado' => 'Operario 9',
                'fecha_realizacion' => '2025-04-20',
                'anotaciones_anteriores' => 'Anotaciones anteriores de la tarea 9',
                'anotaciones_posteriores' => 'Anotaciones posteriores de la tarea 9',
                'fichero_resumen' => 'resumen9.pdf',
            ],
            [
                'client_id' => 10,
                'persona_contacto' => 'Contacto 10',
                'telefono_contacto' => '600778899',
                'descripcion' => 'Descripción de la tarea 10',
                'correo_electronico' => 'contacto10@example.com',
                'direccion' => 'Calle Constelación 505',
                'poblacion' => 'Alicante',
                'codigo_postal' => '03001',
                'provincia' => 10,
                'estado' => 'P',
                'fecha_creacion' => now(),
                'operario_encargado' => 'Operario 10',
                'fecha_realizacion' => '2025-04-25',
                'anotaciones_anteriores' => 'Anotaciones anteriores de la tarea 10',
                'anotaciones_posteriores' => 'Anotaciones posteriores de la tarea 10',
                'fichero_resumen' => 'resumen10.pdf',
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Task::where('correo_electronico', 'like', '%@example.com')->delete();
    }
};
